[package]
name = "libre_sudoku_web_backend"
version = "1.0.0"
edition = "2024"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.104"
web-sys = { version = "0.3.81", features = [
    'HtmlCanvasElement',
    'CanvasRenderingContext2d',
] }
