use crate::board::Board;

pub fn offset_group_col_1(board: &Board) -> Board {
    unsafe {
        [
            [
                *board.get_unchecked(0).get_unchecked(6),
                *board.get_unchecked(0).get_unchecked(7),
                *board.get_unchecked(0).get_unchecked(8),
                *board.get_unchecked(0).get_unchecked(0),
                *board.get_unchecked(0).get_unchecked(1),
                *board.get_unchecked(0).get_unchecked(2),
                *board.get_unchecked(0).get_unchecked(3),
                *board.get_unchecked(0).get_unchecked(4),
                *board.get_unchecked(0).get_unchecked(5),
            ],
            [
                *board.get_unchecked(1).get_unchecked(6),
                *board.get_unchecked(1).get_unchecked(7),
                *board.get_unchecked(1).get_unchecked(8),
                *board.get_unchecked(1).get_unchecked(0),
                *board.get_unchecked(1).get_unchecked(1),
                *board.get_unchecked(1).get_unchecked(2),
                *board.get_unchecked(1).get_unchecked(3),
                *board.get_unchecked(1).get_unchecked(4),
                *board.get_unchecked(1).get_unchecked(5),
            ],
            [
                *board.get_unchecked(2).get_unchecked(6),
                *board.get_unchecked(2).get_unchecked(7),
                *board.get_unchecked(2).get_unchecked(8),
                *board.get_unchecked(2).get_unchecked(0),
                *board.get_unchecked(2).get_unchecked(1),
                *board.get_unchecked(2).get_unchecked(2),
                *board.get_unchecked(2).get_unchecked(3),
                *board.get_unchecked(2).get_unchecked(4),
                *board.get_unchecked(2).get_unchecked(5),
            ],
            [
                *board.get_unchecked(3).get_unchecked(6),
                *board.get_unchecked(3).get_unchecked(7),
                *board.get_unchecked(3).get_unchecked(8),
                *board.get_unchecked(3).get_unchecked(0),
                *board.get_unchecked(3).get_unchecked(1),
                *board.get_unchecked(3).get_unchecked(2),
                *board.get_unchecked(3).get_unchecked(3),
                *board.get_unchecked(3).get_unchecked(4),
                *board.get_unchecked(3).get_unchecked(5),
            ],
            [
                *board.get_unchecked(4).get_unchecked(6),
                *board.get_unchecked(4).get_unchecked(7),
                *board.get_unchecked(4).get_unchecked(8),
                *board.get_unchecked(4).get_unchecked(0),
                *board.get_unchecked(4).get_unchecked(1),
                *board.get_unchecked(4).get_unchecked(2),
                *board.get_unchecked(4).get_unchecked(3),
                *board.get_unchecked(4).get_unchecked(4),
                *board.get_unchecked(4).get_unchecked(5),
            ],
            [
                *board.get_unchecked(5).get_unchecked(6),
                *board.get_unchecked(5).get_unchecked(7),
                *board.get_unchecked(5).get_unchecked(8),
                *board.get_unchecked(5).get_unchecked(0),
                *board.get_unchecked(5).get_unchecked(1),
                *board.get_unchecked(5).get_unchecked(2),
                *board.get_unchecked(5).get_unchecked(3),
                *board.get_unchecked(5).get_unchecked(4),
                *board.get_unchecked(5).get_unchecked(5),
            ],
            [
                *board.get_unchecked(6).get_unchecked(6),
                *board.get_unchecked(6).get_unchecked(7),
                *board.get_unchecked(6).get_unchecked(8),
                *board.get_unchecked(6).get_unchecked(0),
                *board.get_unchecked(6).get_unchecked(1),
                *board.get_unchecked(6).get_unchecked(2),
                *board.get_unchecked(6).get_unchecked(3),
                *board.get_unchecked(6).get_unchecked(4),
                *board.get_unchecked(6).get_unchecked(5),
            ],
            [
                *board.get_unchecked(7).get_unchecked(6),
                *board.get_unchecked(7).get_unchecked(7),
                *board.get_unchecked(7).get_unchecked(8),
                *board.get_unchecked(7).get_unchecked(0),
                *board.get_unchecked(7).get_unchecked(1),
                *board.get_unchecked(7).get_unchecked(2),
                *board.get_unchecked(7).get_unchecked(3),
                *board.get_unchecked(7).get_unchecked(4),
                *board.get_unchecked(7).get_unchecked(5),
            ],
            [
                *board.get_unchecked(8).get_unchecked(6),
                *board.get_unchecked(8).get_unchecked(7),
                *board.get_unchecked(8).get_unchecked(8),
                *board.get_unchecked(8).get_unchecked(0),
                *board.get_unchecked(8).get_unchecked(1),
                *board.get_unchecked(8).get_unchecked(2),
                *board.get_unchecked(8).get_unchecked(3),
                *board.get_unchecked(8).get_unchecked(4),
                *board.get_unchecked(8).get_unchecked(5),
            ],
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::offset_group_col_1;
    use crate::board::board_from_str;

    #[test]
    fn test_offset_group_col_1() {
        assert_eq!(
            offset_group_col_1(&board_from_str([
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
            ])),
            board_from_str([
                "789123456",
                "789123456",
                "789123456",
                "789123456",
                "789123456",
                "789123456",
                "789123456",
                "789123456",
                "789123456",
            ]),
        );
    }
}
