use crate::board::Board;

pub fn offset_group_col_2(board: &Board) -> Board {
    unsafe {
        [
            [
                *board.get_unchecked(0).get_unchecked(3),
                *board.get_unchecked(0).get_unchecked(4),
                *board.get_unchecked(0).get_unchecked(5),
                *board.get_unchecked(0).get_unchecked(6),
                *board.get_unchecked(0).get_unchecked(7),
                *board.get_unchecked(0).get_unchecked(8),
                *board.get_unchecked(0).get_unchecked(0),
                *board.get_unchecked(0).get_unchecked(1),
                *board.get_unchecked(0).get_unchecked(2),
            ],
            [
                *board.get_unchecked(1).get_unchecked(3),
                *board.get_unchecked(1).get_unchecked(4),
                *board.get_unchecked(1).get_unchecked(5),
                *board.get_unchecked(1).get_unchecked(6),
                *board.get_unchecked(1).get_unchecked(7),
                *board.get_unchecked(1).get_unchecked(8),
                *board.get_unchecked(1).get_unchecked(0),
                *board.get_unchecked(1).get_unchecked(1),
                *board.get_unchecked(1).get_unchecked(2),
            ],
            [
                *board.get_unchecked(2).get_unchecked(3),
                *board.get_unchecked(2).get_unchecked(4),
                *board.get_unchecked(2).get_unchecked(5),
                *board.get_unchecked(2).get_unchecked(6),
                *board.get_unchecked(2).get_unchecked(7),
                *board.get_unchecked(2).get_unchecked(8),
                *board.get_unchecked(2).get_unchecked(0),
                *board.get_unchecked(2).get_unchecked(1),
                *board.get_unchecked(2).get_unchecked(2),
            ],
            [
                *board.get_unchecked(3).get_unchecked(3),
                *board.get_unchecked(3).get_unchecked(4),
                *board.get_unchecked(3).get_unchecked(5),
                *board.get_unchecked(3).get_unchecked(6),
                *board.get_unchecked(3).get_unchecked(7),
                *board.get_unchecked(3).get_unchecked(8),
                *board.get_unchecked(3).get_unchecked(0),
                *board.get_unchecked(3).get_unchecked(1),
                *board.get_unchecked(3).get_unchecked(2),
            ],
            [
                *board.get_unchecked(4).get_unchecked(3),
                *board.get_unchecked(4).get_unchecked(4),
                *board.get_unchecked(4).get_unchecked(5),
                *board.get_unchecked(4).get_unchecked(6),
                *board.get_unchecked(4).get_unchecked(7),
                *board.get_unchecked(4).get_unchecked(8),
                *board.get_unchecked(4).get_unchecked(0),
                *board.get_unchecked(4).get_unchecked(1),
                *board.get_unchecked(4).get_unchecked(2),
            ],
            [
                *board.get_unchecked(5).get_unchecked(3),
                *board.get_unchecked(5).get_unchecked(4),
                *board.get_unchecked(5).get_unchecked(5),
                *board.get_unchecked(5).get_unchecked(6),
                *board.get_unchecked(5).get_unchecked(7),
                *board.get_unchecked(5).get_unchecked(8),
                *board.get_unchecked(5).get_unchecked(0),
                *board.get_unchecked(5).get_unchecked(1),
                *board.get_unchecked(5).get_unchecked(2),
            ],
            [
                *board.get_unchecked(6).get_unchecked(3),
                *board.get_unchecked(6).get_unchecked(4),
                *board.get_unchecked(6).get_unchecked(5),
                *board.get_unchecked(6).get_unchecked(6),
                *board.get_unchecked(6).get_unchecked(7),
                *board.get_unchecked(6).get_unchecked(8),
                *board.get_unchecked(6).get_unchecked(0),
                *board.get_unchecked(6).get_unchecked(1),
                *board.get_unchecked(6).get_unchecked(2),
            ],
            [
                *board.get_unchecked(7).get_unchecked(3),
                *board.get_unchecked(7).get_unchecked(4),
                *board.get_unchecked(7).get_unchecked(5),
                *board.get_unchecked(7).get_unchecked(6),
                *board.get_unchecked(7).get_unchecked(7),
                *board.get_unchecked(7).get_unchecked(8),
                *board.get_unchecked(7).get_unchecked(0),
                *board.get_unchecked(7).get_unchecked(1),
                *board.get_unchecked(7).get_unchecked(2),
            ],
            [
                *board.get_unchecked(8).get_unchecked(3),
                *board.get_unchecked(8).get_unchecked(4),
                *board.get_unchecked(8).get_unchecked(5),
                *board.get_unchecked(8).get_unchecked(6),
                *board.get_unchecked(8).get_unchecked(7),
                *board.get_unchecked(8).get_unchecked(8),
                *board.get_unchecked(8).get_unchecked(0),
                *board.get_unchecked(8).get_unchecked(1),
                *board.get_unchecked(8).get_unchecked(2),
            ],
        ]
    }
}

#[cfg(test)]
mod tests {
    use super::offset_group_col_2;
    use crate::board::from_str;

    #[test]
    fn test_offset_group_col_2() {
        assert_eq!(
            offset_group_col_2(&from_str([
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
                "123456789",
            ])),
            from_str([
                "456789123",
                "456789123",
                "456789123",
                "456789123",
                "456789123",
                "456789123",
                "456789123",
                "456789123",
                "456789123",
            ]),
        );
    }
}
